### ISSUE TITLE
탐색 카테고리 뷰 구현

### ISSUE THREAD

**Issue by SeonHwan-Kim** [gosopt-LionHeart/LionHeart-AOS#19]
## *To-do*
- 화면 이동
  - [x] 각 카테고리 클릭 시 그 카테고리 페이지 넘어가기

- 뷰 이름
  - [x] 이동한 뷰 이름 확인

 - 아티클
   - [x] item 뷰 구현
   - [x] 북마크
   - [x] 상단 흐리게

## *Reference*
- [ ] 참고자료 링크

**Comment by daehwan2da** [comment]
#22 확인 부탁드리겠습니다
- Search Fragment 에서 Top Nav 제거해주세요
